// Snapshot consumed by CustomerStateHost. Combines the persisted TransactionState with
// non-persisted live data (running litres, generated payment ref, QR payload).
package app.balancee.smartpump.display.ui.screens.customer

import androidx.compose.runtime.Immutable
import app.balancee.smartpump.display.domain.model.DeviceConfig
import app.balancee.smartpump.display.domain.model.TransactionState

@Immutable
data class CustomerUiState(
    val state: TransactionState,
    val config: DeviceConfig,
    /** Running litres dispensed during a Dispensing state. */
    val liveLitres: Double = 0.0,
    /** Running Naira amount during a Dispensing state. */
    val liveAmountKobo: Long = 0L,
    /** Generated by PaymentProcessor — shown on AwaitingPayment as "Txn BLC-NNNNN". */
    val transactionRef: String? = null,
    /** Payload encoded into the QR for BANK_QR / BALANCEE_APP. */
    val qrPayload: String? = null,
)
